"""empty message

Revision ID: 240d54fe25a5
Revises: b8535a0c534f
Create Date: 2024-12-09 14:09:06.525665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240d54fe25a5'
down_revision: Union[str, None] = 'b8535a0c534f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    '''op.create_table('tokensplash_accs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bought', sa.Float(), nullable=True),
    sa.Column('sold', sa.Float(), nullable=True),
    sa.Column('bybit_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bybit_account_id'], ['bybit_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )'''
    '''op.create_foreign_key(None, 'ts_accounts', 'bybit_account', ['b_ac_id'], ['id'])
    op.drop_column('ts_accounts', 'bybit_account_id')
    op.drop_column('ts_accounts', 'bybit_acc_id')'''
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    '''op.add_column('ts_accounts', sa.Column('bybit_acc_id', sa.INTEGER(), nullable=True))
    op.add_column('ts_accounts', sa.Column('bybit_account_id', sa.INTEGER(), nullable=True))'''
    '''op.drop_constraint(None, 'ts_accounts', type_='foreignkey')'''
    '''op.drop_table('tokensplash_accs')'''
    # ### end Alembic commands ###
