"""empty message

Revision ID: 4213b62c7b18
Revises: 9dad47bbc334
Create Date: 2024-11-15 15:19:31.711395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4213b62c7b18'
down_revision: Union[str, None] = '9dad47bbc334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bybit_account', sa.Column('is_password_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bybit_account', 'is_password_changed')
    # ### end Alembic commands ###
