"""empty message

Revision ID: 5c26079754d0
Revises: 6d988a757b97
Create Date: 2024-12-03 21:17:40.415780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c26079754d0'
down_revision: Union[str, None] = '6d988a757b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bybit_account', sa.Column('deposit_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bybit_account', 'deposit_amount')
    # ### end Alembic commands ###
