"""empty message

Revision ID: 6d988a757b97
Revises: 7c46421409ba
Create Date: 2024-12-03 20:25:18.107083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d988a757b97'
down_revision: Union[str, None] = '7c46421409ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bybit_account', sa.Column('first_deposit_date', sa.Date(), nullable=True))
    op.add_column('bybit_account', sa.Column('trading_volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bybit_account', 'trading_volume')
    op.drop_column('bybit_account', 'first_deposit_date')
    # ### end Alembic commands ###
