"""empty message

Revision ID: 7c46421409ba
Revises: a837d981cce1
Create Date: 2024-11-23 20:34:45.497253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c46421409ba'
down_revision: Union[str, None] = 'a837d981cce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bybit_account', sa.Column('is_ts_completed', sa.Boolean(), nullable=True))
    op.add_column('bybit_account', sa.Column('has_ts_mark', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bybit_account', 'has_ts_mark')
    op.drop_column('bybit_account', 'is_ts_completed')
    # ### end Alembic commands ###
