"""empty message

Revision ID: a837d981cce1
Revises: 4213b62c7b18
Create Date: 2024-11-16 00:24:46.567262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a837d981cce1'
down_revision: Union[str, None] = '4213b62c7b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bybit_account', sa.Column('last_ts_registered', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bybit_account', 'last_ts_registered')
    # ### end Alembic commands ###
