"""empty message

Revision ID: cbf3bdff3eb1
Revises: 240d54fe25a5
Create Date: 2024-12-09 14:57:54.882261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf3bdff3eb1'
down_revision: Union[str, None] = '240d54fe25a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ts_accounts', 'bybit_acc_id')
    op.drop_column('ts_accounts', 'bybit_account_id')
    op.drop_column('ts_accounts', 'b_ac_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ts_accounts', sa.Column('b_ac_id', sa.INTEGER(), nullable=True))
    op.add_column('ts_accounts', sa.Column('bybit_account_id', sa.INTEGER(), nullable=True))
    op.add_column('ts_accounts', sa.Column('bybit_acc_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
